[package]
name = "dwarfs"
version = "0.1.0"
authors = ["Jakob <jakobfischer93@gmail.com>"]

[dependencies]
gl = "0.11"
glutin = "0.19"
glm = "0.2"
log = "0.4"
env_logger = "0.6"
chrono = "0.4"
rand = "0.6"
image = "0.20"
num-traits = "0.2"
